import { LOGO_COMPONENT_COUNT } from "@/features/mission-ascent/config/missionAssembly";
import type { HudSnapshot } from "@/features/mission-ascent/types/mission.types";

export const defaultHudSnapshot: HudSnapshot = {
  altitudeKm: 0,
  zoneId: "launch-corridor",
  zoneLabel: "Launch Corridor",
  score: 0,
  fuel: 100,
  heat: 0,
  integrity: 3,
  maxIntegrity: 3,
  shield: false,
  chain: 0,
  chainMultiplier: 1,
  chainTimerMs: 0,
  chainMaxMs: 4800,
  throttle: 0.42,
  requestedThrottle: 0.42,
  throttleZone: "cruise",
  throttleDisabled: false,
  noFuel: false,
  fuelDisplay: "100%",
  timerSeconds: 120,
  overheated: false,
  cooling: false,
  eventTitle: null,
  eventHint: null,
  zoneToast: null,
  chainLostMessage: null,
  pickupFlash: null,
  timedPhase: "warmup",
  finaleActive: false,
  phase: "launch-sequence",
  assemblyCollected: [],
  assemblyMissed: [],
  nextComponent: "d",
  componentsCollected: 0,
  componentsMissed: 0,
  totalComponents: LOGO_COMPONENT_COUNT,
  assemblyComplete: false,
  componentToast: null,
  signalBoostActive: false,
  signalBoostRemainingMs: 0,
  signalBoostMultiplier: 1,
  scoreMultiplier: 1,
  sectorNumber: 1,
  sectorName: "Launch Corridor",
  sectorSubtitle: "Flight systems online",
  sectorCycle: 0,
  isExtendedMission: false,
  sectorsCompleted: 0,
  sectorTimeRemainingMs: 120_000,
  sectorState: "playing",
  sectorTransitionMessage: null,
  sectorTransitionSubtext: null,
  sectorCompleteSummary: null,
  timerUrgent: false,
  timerCritical: false,
  difficultyLabel: "STABLE",
  maxSectorsThisRun: 5,
  logosCompleted: 0,
  highestSectorThisRun: 1,
};
